### ISSUE TITLE
i18n checklist for Working with time

### ISSUE THREAD

**Issue by ToruKawaguchi** [w3c/wot-thing-description#578]
This is to check compliance of TD spec against i18n check list: "Working with time" part as of <https://www.w3.org/International/techniques/developing-specs.en?open=locale#locale>.

In TD, only fields `created` and `lastModified` is relavant to time.

<https://w3c.github.io/wot-thing-description/#thing>

- `created`: Provides information when the TD instance was created.
- `lastModified`: Provides information when the TD instance was last modified.

Both are defined as `dateTime` and is serialized into XSD built in `dateTime` datatype <https://www.w3.org/TR/xmlschema11-2/#dateTime-lexical-mapping>, with lexical form `YYYY-MM-DDThh:mm:ssZ`.

<https://w3c.github.io/wot-thing-description/#td-basic-types-mapping>

Checklist below (taken from here: <https://w3c.github.io/bp-i18n-specdev/#ghChecklist>) was checked based on above assumption: 

### Working with time
1. [x] <a class="self" href="#loc_time_preCE">​</a>When defining calendar and date systems, be sure to allow for dates prior to the common era, or at least define handling of dates outside the most common range.
  [Comment] Both `created` and `lastModified` is for TD instance itself, therefore the dates prior to the common era are not relavant.
1. [x] <a class="self" href="#loc_time_utc">​</a>When defining time or date data types, ensure that the time zone or relationship to UTC is always defined.
  [Comment] `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` is UTC.
1. [x] <a class="self" href="#loc_time_floating">​</a>Provide a health warning for conversion of time or date data types that are "floating" to/from incremental types, referring as necessary to the <a href="https://www.w3.org/TR/timezone/"><cite>Time Zones</cite> WG Note</a>.  <a href="https://www.w3.org/TR/timezone/">more</a>
  [Comment] `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` is NOT a floating time.
1. [x] <a class="self" href="#loc_time_leapsec">​</a>Allow for leap seconds in date and time data types.  <a href="https://w3c.github.io/bp-i18n-specdev/#loc_time_leapsec">more</a>
 [Comment] Thing Description referes to `dateTime` in XSD Version 1.1 and it does not allow leap-seconds.  RESOLUTION: Timestamps are used for applications in the TD that do not require high accuracy, such as TD creation time.   If payloads need high accuracy they can define their own (non-xsd) time format.  So we have decided to stay with XSD dateTime ... even though it does not support leap seconds.
1. [x] <a class="self" href="#loc_time_consistency">​</a>Use consistent terminology when discussing date and time values. Use 'floating' time for time zone independent values.
  [Comment] `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` is NOT a floating time.
1. [x] <a class="self" href="#loc_time_zone_offset">​</a>Keep separate the definition of time zone from time zone offset.
  [Comment] `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include time zone definition.
1. [x] <a class="self" href="#loc_time_zone_ids">​</a>Use IANA time zone IDs to identify time zones. Do not use offsets or LTO as a proxy for time zone.
  [Comment] `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include time zone definition.
  HOWEVER, it was noted in the i18n call that disallowing offsets might cause interoperability problems, so it is better to still allow them, even if timezones themselves are not to be used.
1. [x] <a class="self" href="#loc_time_zone_field">​</a>Use a separate field to identify time zone.
  [Comment] `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include time zone definition
1. [x] <a class="self" href="#loc_time_week">​</a>When defining rules for a "week", allow for culturally specific rules to be applied.  <a href="https://w3c.github.io/bp-i18n-specdev/#loc_time_week">more</a>
  [Comment] `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include concept of week.
1. [x] <a class="self" href="#loc_time_week_number">​</a>When defining rules for week number of year, allow for culturally specific rules to be applied.
  [Comment] `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include concept of week.
1. [x] <a class="self" href="#loc_time_13">​</a>When non-Gregorian calendars are permitted, note that the "month" field can go to 13 (undecimber).
  [Comment] `dateTime` only uses Gregorian calendar.

### Remaining issues: 

- Do we need to be more explicit that TD only allows UTC? (final 'Z' in the form `YYYY-MM-DDThh:mm:ssZ`).
  -> (Result from 26th April TD call) Victor will add clarification Text.
- How should we handle leap seconds in TD?  
  -> (Result from 26th April TD call) change comment as above and leave checkbox unchecked.

**Comment by ToruKawaguchi** [comment]
In TD, only fields `created` and `lastModified` is relavant to time.

<https://w3c.github.io/wot-thing-description/#thing>

- `created`: Provides information when the TD instance was created.
- `lastModified`: Provides information when the TD instance was last modified.

Both are defined as `dateTime` and is serialized into XSD built in `dateTime` datatype <https://www.w3.org/TR/xmlschema11-2/#dateTime-lexical-mapping>, with lexical form `YYYY-MM-DDThh:mm:ssZ`.

<https://w3c.github.io/wot-thing-description/#td-basic-types-mapping>


### Comments to each items: 

- When defining calendar and date systems, be sure to allow for dates prior to the common era, or at least define handling of dates outside the most common range.
  - Both `created` and `lastModified` is for TD instance itself, therefore the dates prior to the common era are not relavant.

- When defining time or date data types, ensure that the time zone or relationship to UTC is always defined.
  - `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` is UTC.a

- ​Provide a health warning for conversion of time or date data types that are "floating" to/from incremental types, referring as necessary to the Time Zones WG Note. more
  - `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` is NOT a floating time.

- ​Allow for leap seconds in date and time data types. more
  - `dateTime` does not allow leap-seconds. Don't know whether it is necessary for TD to handle this.

- ​Use consistent terminology when discussing date and time values. Use 'floating' time for time zone independent values.
  - `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` is NOT a floating time.

- ​Keep separate the definition of time zone from time zone offset.
  - `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include time zone definition.

- ​Use IANA time zone IDs to identify time zones. Do not use offsets or LTO as a proxy for time zone.
  - `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include time zone definition.

- ​Use a separate field to identify time zone.
  - `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include time zone definition.

- ​When defining rules for a "week", allow for culturally specific rules to be applied. more
  - `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include concept of week.

- ​When defining rules for week number of year, allow for culturally specific rules to be applied.
  - `dateTime` with form `YYYY-MM-DDThh:mm:ssZ` does not include concept of week.

- ​When non-Gregorian calendars are permitted, note that the "month" field can go to 13 (undecimber).
  - `dateTime` only uses Gregorian calendar.

### Remaining issues: 

- Do we need to be more explicit that TD only allows UTC? (final 'Z' in the form `YYYY-MM-DDThh:mm:ssZ`).
- How should we handle leap seconds in TD?

**Comment by mmccool** [comment]
- leap seconds: xsd:datetime does not support this
- BUT need leap seconds for very accurate timekeeping
- BUT our timestamp usage is not for that, but for document management, not payloads
resolution: we don't need to worry about leap seconds.

**Comment by mmccool** [comment]
- Also, it was noted that disallowing offsets may cause interoperability problems; so we should allow them (or rather, don't disallow them) even if we do not support encoding of timezones.

**Comment by mkovatsc** [comment]
Time zone offsets are allowed but discouraged with a SHOULD on using Zulu time.
High-precision time stamping that would need leap seconds is not in scope for this spec.

Closing.
