### ISSUE TITLE
i18n checklist for Working with personal names

### ISSUE THREAD

**Issue by chachamimm** [w3c/wot-thing-description#580]
There are not expressly tags that personal names are used in TD. UTF-8 is used in TD. Therefore, language that is supported by UTF-8 can be used. So Personal name can be used. But it is used as a part of a sentence.

### Working with personal names
1. [x] <a class="self" href="#loc_names_given_family">​</a>Check whether you really need to store or access given name and family name separately.  <a href="https://www.w3.org/International/questions/qa-personal-names#singlefield">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_limits">​</a>Avoid placing limits on the length of names, or if you do, make allowance for long strings.  <a href="https://www.w3.org/International/questions/qa-personal-names#singlefield">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_first_last">​</a>Try to avoid using the labels 'first name' and 'last name' in non-localized contexts.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_extra_fields">​</a>Consider whether it would make sense to have one or more extra fields, in addition to the full name field, where users can provide part(s) of their name that you need to use for a specific purpose.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_how_contact">​</a>Allow for users to be asked separately how they would like you be addressed when someone contacts them.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_relevant_info">​</a>If parts of a person's name are captured separately, ensure that the separate items can capture all relevant information.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_algorithms">​</a>Be careful about assumptions built into algorithms that pull out the parts of a name automatically.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_initials">​</a>Don't assume that a single letter name is an initial.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_famname_reqd">​</a>Don't require that people supply a family name.  <a href="https://www.w3.org/International/questions/qa-personal-names#splitting">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_punctuation">​</a>Don't forget to allow people to use punctuation such as hyphens, apostrophes, etc. in names.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_uppercase">​</a>Don't require names to be entered all in upper case.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_spaces">​</a>Allow the user to enter a name with spaces.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_same_names">​</a>Don't assume that members of the same family will share the same family name.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_nee">​</a>It may be better for a form to ask for 'Previous name' rather than 'Maiden name' or 'née'.  <a href="https://www.w3.org/International/questions/qa-personal-names#otherthings">more</a>

     [COMMENT] Personal names are not used in TD.

1. [x] <a class="self" href="#loc_names_latin_native">​</a>You may want to store the name in both Latin and native scripts, in which case you probably need to ask the user to submit their name in both native script and Latin-only form, as separate items.  <a href="https://www.w3.org/International/questions/qa-personal-names#encoding">more</a>

     [COMMENT] Personal names are not used in TD.

**Comment by mmccool** [comment]
"Personal names not being used in TDs" is not COMPLETELY true.  There might be support metadata, for example, that mentions a person by name (although I think we should specify this should be a contact email, not a name anyhow).   However, I agree that none of the above issues apply even to the provision of a contact name, since it would just be a UTF-8 string without any imposed structure.

**Comment by takuki** [comment]
During 4/26 telecon, it was suggested to modify the comment to additionally say that we have a field (i.e. support) that can contain names but we do not enforce any format or process them.

**Comment by mmccool** [comment]
We have decided to require that "support" we a URI/IRI rather than a human-readable string that might contain a personal name.  Therefore the exception I noted above has been resolved.

**Comment by mkovatsc** [comment]
All was checked.
Follow-up was clarified.
Closing.
