### ISSUE TITLE
i18n checklist for "Defining language values"

### ISSUE THREAD

**Issue by ashimura** [w3c/wot-thing-description#595]
### Defining language values
1. [x] <a class="self" href="#lang_use_bcp47">​</a>Values for language declarations must use BCP 47. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_values">more</a>
1. [x] <a class="self" href="#lang_bcp_not_rfc">​</a>Refer to BCP 47, not to RFC 5646. <a class="local" href="https://w3c.github.io/bp-i18n-specdev/#sec_lang_values">more</a>
1. [x] <a class="self" href="#lang_values_valid">​</a>Be specific about what level of conformance you expect for language tags. The word "valid" has special meaning in BCP 47. Generally "well-formed" is a better choice.
    - we generally say "The value MUST be a well-formed BCP47 tag." instead of "as defined"
    - we also require the use of a script subtag when necessary to infer text direction, using az-Latn vs az-Arab as an example
1. [x] <a class="self" href="#lang_matching_bcp">​</a>Reference BCP47 for language tag matching.
    - need to add a description on language tag matching?
      resolution: no, implementors can define their own language negotiation rules

**Comment by mkovatsc** [comment]
All was checked. Closing.
