### ISSUE TITLE
Checklist for collected issues

### ISSUE THREAD

**Issue by mkovatsc** [w3c/wot-thing-description#671]
- [ ] "by combing the data schemas of each PropertyAffordances instance" -- remove plural s
- [ ] "each value assigned to their op name-value pair" -- "the string values assigned to the name op, either directly or within an Array, "
- [ ] Move text on SemVer in 6.3.3 to Version class definition in Section 5
- [ ] "PropertyAffordance Class is a subclass of the class InteractionAffordance" -- "PropertyAffordance is a Subclass of the InteractionAffordance Class"
- [ ] "Metadata specifying that the array data type is used by the data schema" -- "Metadata describing data of type Array. This Subclass is indicated by the Term array assigned to type of DataSchema instances"
- [ ] Default Value Definitions need markup like in class definitions for Type
- [x] "Thing Description instances are modeled and structured" -- "WoT Thing Descriptions represent Things and are modeled and structured"
- [ ] "JSON-based representation format for Things, a serialization of the TD Information Model" -- fix
- [ ] "a serialization of the TD Information Model" -- "a serialization of instances of the Class Thing defined by the TD Information Model."
- [ ] readOnly and writeOnly need Default Value "false" @sebastiankb takes care of it

**Comment by sebastiankb** [comment]
> readOnly and writeOnly need Default Value "false"
if we integrage this egain we have to update  example https://w3c.github.io/wot-thing-description/#example-3

**Comment by sebastiankb** [comment]
there is a PR that address all listed issues #677

**Comment by mmccool** [comment]
PR merged, will mark closed prior to CR transition.
